name: 'update doc'

on:
  pull_request:
    branches:
      - main
    types: [closed]
  workflow_call:

permissions:
  contents: write

jobs:
  update-doc:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install
        run: npm install typedoc typedoc-plugin-markdown -g

      - name: Documents Update
        run: typedoc --plugin typedoc-plugin-markdown ./src/**/*.ts

      - name: Commit & Push
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "github-actions"
          git add ./docs
          git commit -m "Doc Auto Update"
          git push origin main
